### PR TITLE
Test release target of Makefile

### PR DESCRIPTION
**Pull request by sam-github**

### CODE REVIEW

**Comment by sam-github** [comment]
`git clean -x -d && sh autogen.sh && ./configure && make release` fails for me, so lets see if I can repro with Travis.

Error:
```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
To disable silent build and print the full command line of every stage

        make V=1

To build/update the documentation

        make doc

make  dist-gzip dist-zip am__post_remove_distdir='@:'
make  distdir-am
if test -d "libnet-1.2-rc4"; then find "libnet-1.2-rc4" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "libnet-1.2-rc4" || { sleep 5 && rm -rf "libnet-1.2-rc4"; }; else :; fi
test -d "libnet-1.2-rc4" || mkdir "libnet-1.2-rc4"
 (cd include && make  top_distdir=../libnet-1.2-rc4 distdir=../libnet-1.2-rc4/include \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make  distdir-am
 (cd src && make  top_distdir=../libnet-1.2-rc4 distdir=../libnet-1.2-rc4/src \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make  distdir-am
 (cd win32 && make  top_distdir=../libnet-1.2-rc4 distdir=../libnet-1.2-rc4/win32 \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make  distdir-am
 (cd doc && make  top_distdir=../libnet-1.2-rc4 distdir=../libnet-1.2-rc4/doc \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make  distdir-am
 (cd man && make  top_distdir=../../libnet-1.2-rc4 distdir=../../libnet-1.2-rc4/doc/man \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make  distdir-am
 (cd man1 && make  top_distdir=../../../libnet-1.2-rc4 distdir=../../../libnet-1.2-rc4/doc/man/man1 \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[7]: *** No rule to make target 'distdir'.  Stop.
```

`make doc` has warnings, but that's probably not the root cause:
```
  DXGEN  Doxyfile
warning: tag INPUT: input source `./doc/libnet_api_main_page.md' does not exist
warning: source ./doc/libnet_api_main_page.md is not a readable file or directory... skipping.
/home/sam/p/libnet/include/libnet/libnet-functions.h:281: warning: parameters of member libnet_addr2name6_r are not (all) documented
/home/sam/p/libnet/include/libnet/libnet-functions.h:2361: warning: return type of member libnet_cq_end_loop is not documented
  GEN      doc
Finalizing man pages...
Done.
/home/sam/p/libnet
```

**Comment by troglobit** [comment]
Great stuff! I was thinking the other day what else we could add to Travis, and unrelated I thought about extending the release target with more sanity checks.  Obvious solution, thanks merging! :)

**Comment by troglobit** [comment]
I've fixed a few of the issues you identified, but it seems we're running into a bit of a problem with the policy "distribute man pages, but not have them in GIT".  Actually it's the distcheck  target that fails to build the man pages atm.  Working on it :)

**Comment by troglobit** [comment]
As I mentioned in #46, everything should be fixed now on the latest master, 065467e.

**Pull request merged**
