### PR TITLE
improved suggested MSVC x64 support (Pull Request #58) + other tiny fixes

### PR DESCRIPTION
**Pull request by sgeto**
Creating two separate batch files for x86 and x64 compilation as suggested in [#58](https://github.com/sam-github/libnet/pull/58) by robertolarcher (by renaming the original and creating a new one) breaks the Linux and OSX? building processes. 
x64 support is useful and very much in order and I also like the way the new batch files don't dump everything into the src folder. 
Here's my approach.
A new, fancy batch file, with the same name, that takes three (optional) arguments (x86, x64 or x86_x64) and set the appropriate path and environment variables.

Works as expected on a fresh Ubuntu, Windows running VS2015... Not sure though what [Travis'](https://travis-ci.org/sgeto/libnet/jobs/176572670) problem is...

### CODE REVIEW

**Comment by sgeto** [comment]
Travis build is passing now [yay!](https://travis-ci.org/sgeto/libnet)

**Comment by sam-github** [comment]
@sgeto, @barak What is current state of this? I'm not so familiar with autotools, and am on leave and don't have a Windows or Linux system, so its hard to evaluate. Should I merge this? With #49, or does it incorporate #49? It looks like it replaces #58, yes?

**Comment by sgeto** [comment]
> What is the current state of this?

I've been building with these changes ever since I added them on both Linux and windows. I don't have a macOS, but the Continuous Integration I added show that it builds and installs there as well. Actually, on the buildbot, I've set up that builds are only marked as succeeded if the commands "configure", "make", "make install" and "make distcheck" exit with 0.
The latter doesn't. It's not a big deal or even necessary, and I've started to take care of that in a separate branch.

As far as I'm concerned, this PR could be merged. And yes, it incorporate #49 and replaces #58.
If you spot something in my commits that you don't like/want, let me know.

Ever since my last commit, I've added/changed a few more things locally. It's probably a good idea to commit these after getting this out of the way.

"We are saddened by a bird's cry, but not for a fish's blood.
Blessed are those with voices."

-Mamoru Oshii

**Comment by sam-github** [comment]
Having some trouble building on OS X:

```
Making all in src
  CC       libnet_link_bpf.lo
libnet_link_bpf.c:47:10: fatal error: 'bpf.h' file not found
#include <bpf.h>
         ^~~~~~~
1 error generated.
make[1]: *** [libnet_link_bpf.lo] Error 1
make: *** [all-recursive] Error 1
libnet/libnet (sgeto % u=) %
```

Doesn't happen on master, just this branch. No time to look further right now.

**Comment by sam-github** [comment]
It's because `-I ../include` isn't in the CC flags, can you fix this?

```
libnet/libnet (sgeto % u=) % make -C src libnet.la
  CC       libnet_link_bpf.lo
libnet_link_bpf.c:47:10: fatal error: 'bpf.h' file not found
#include <bpf.h>
         ^~~~~~~
1 error generated.
make: *** [libnet_link_bpf.lo] Error 1
libnet/libnet (sgeto % u=) % make -C src libnet.la -n
echo "  CC      " libnet_link_bpf.lo;/bin/sh ../libtool --silent --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H      -O0 -g -Wall --coverage -c -o libnet_link_bpf.lo libnet_link_bpf.c
```

Btw, hiding the commands that are run looks good when nothing goes wrong, but makes trouble-shooting hard. Is there a better way to get the generated makefile to show me more detail than `  CC       libnet_link_bpf.lo` other than by using `make -n`?

**Comment by sam-github** [comment]
Looking forward to the Travis support, that will be fabulous.

**Comment by sgeto** [comment]
> Is there a better way to get the generated makefile to show me more detail than CC libnet_link_bpf.lo other than by using make -n?

Yes. The build system has a dedicated flag for that: `--enable-silent-rules` (default) or `--disable-silent-rules` you can these to the configure script.
Even better is to simply type `make V=1` to see the full command line.
I added a note about that at the end of the Configuration Summary:
`To disable silent building and print the full command line of every stage, run "make V=1"
`
> It's because -I ../include isn't in the CC flags, can you fix this?

How would you like me to fix it? Would changing:
#include <bpf.h>
to
`#include "../include/bpf.h"
be fine?
`

**Comment by sam-github** [comment]
Do you have access to a linux box to check how it used to work? Was ../include only added based on some conditions, such as the O/S, or whether bpf.h is in the system include path?

If ../include was in the -I path for all systems, then we know this file always used libnet's version of bpf.h, and hard-coding the local path is fine.

If ../include was only added for some OS or some conditions, then its probably better to copy the checks from the old auto* to the new ones.

**Comment by sgeto** [comment]
[common.h](https://github.com/sam-github/libnet/blob/master/libnet/src/common.h#L50) adds libnet,h, and config.h the same way. 

At some point, I've decided to drop [Makefile.am.common](https://github.com/sam-github/libnet/commit/790e4b0b1b137a5c036a0407f864bf71bc69bf5d) because its use case is outdated and I wrongly assumed that the one flag it contains isn't needed.
I stand corrected. At the same time, I am also not sure why libnet needs to ship a `bpf.h` at all.
Anyways, either way is fine with me. I can add that flag back or we can simply do a `#include "../include/bpf.h"`

> Do you have access to a linux box to check how it used to work?

This PR comes with rudimentary travis support for Linux and macOS.
Until merger, you should be able to follow build step from my [fork](https://travis-ci.org/sgeto/libnet)
**Again**: It will look like Linux is failing. It isn't. On;y the last command `make distcheck` which is something  I wanted to have around is. I wanted to take care of that a while ago but didn't get to.
The dedicated branch/PR for that is found [here](https://github.com/sgeto/libnet/pull/1).

**Comment by sam-github** [comment]
>  I am also not sure why libnet needs to ship a bpf.h at all.

I assume its because OS X doesn't have that header even with xcode installed, but the kernel still supports the facility. One version of your .travis stanzas for OS X did a `brew install libpcap` IIRC, which does get a `bpf..h` installed, but homebrew plus a non-standard install is a heavy dependency.

I can't see the build flags from travis, https://travis-ci.org/sgeto/libnet/jobs/388388628 has only the stripped down output. I would like to know whether on master, when building for linux, `-I ../include` is in the compiler CFLAGS, or whether `-I../include` is only added for OS X. Do you know? Can you tell?

Sorry, I had my linux laptop taken away when I went on leave - it will be a few months until I get it back. That's why I have no access to linux machines, real or virtual, at the moment.

**Comment by sgeto** [comment]
> homebrew plus a non-standard install is a heavy dependency

I totally agree.

> I would like to know whether on master, when building for Linux, -I ../include is in the compiler CFLAGS, or whether -I../include is only added for OS X. Do you know? Can you tell?

Libnet currently doesn't build with `-I ../include` on any platform. I know because 1. I rewrote most of it, and 2. the [CFLAGS section in the Configuration Summary](https://travis-ci.org/sgeto/libnet/jobs/388388628#L983) would tell you.

I tuned the [Prepare script](https://travis-ci.org/sgeto/libnet/jobs/388388628#L983) a bit a bit to include a few additional flags. This is how you would add all sorts of flags on the fly without hardcoding them.

> Sorry, I had my Linux laptop taken away when I went on leave

No problem. I can make the Travis output more verbose by default. In fact, I'll do that once I get home.

**Comment by barak** [comment]
To check if you have the right -I xxx flags, you also need to:
```
./autogen.sh
mkdir b
cd b
../configure
make
```
to do an "out of tree" build.

This facility also makes it easier to build with different sets of options from the same source tree, without stepping on your own toes.

**Comment by koeppea** [comment]
> Looking forward to the Travis support, that will be fabulous.
> 

It does actually support building osx.

**Comment by sgeto** [comment]
@barak thanks for the hint. I prepared something. Let's see if we get the desired results.

> It does actually support building osx.

It does, doesn't it? :-)
@koeppea can you build this PR on your FreeBSD box, please?

**Comment by barak** [comment]
I think some of the fixes you're doing are already in https://github.com/barak/libnet branch master, which merges cleanly with https://github.com/sam-github/libnet branch master

**Comment by sgeto** [comment]
True. We're overlapping. This PR also got a bit weird. I'm not sure where these duplicated commits are coming from.
If it's about being clean, I can just close this import my commits to a new PR. 
But it's more about which PR is better. And since mine incorporates your changed the answer is that is pretty obvious.

**Comment by barak** [comment]
Yeah, I just forward-ported the one missing thing, with a bit of a rewrite, on top of your branch.

**Comment by sgeto** [comment]
Linux builds are passing now. 👍  https://travis-ci.org/sgeto/libnet

**Comment by sam-github** [comment]
@sgeto I think you missed my question:

> I would like to know whether ***on master***, when building for Linux, -I ../include is in the compiler CFLAGS, or whether -I../include is only added for OS X. Do you know? Can you tell?

You told me how it works after your rewrite, but I'm asking how it *used to work* (and as I explained, I can't figure it out myself because I don't have linux access ATM).

**Comment by sam-github** [comment]
OK, that means that libnet was always using it's internal `bpf.h`, so I think we can always include `../include/bpf.h` directly.

**Comment by sgeto** [comment]
Got it. I did that and also added the include flag back. It's probably better this way so that the build doesn't include a foreign libnet.h first.

I am seeing a lot duplicated commits. I think some clean up is in order...

**Comment by sam-github** [comment]
Yeah, something happened in the history, it needs some rebasing, won't even merge ATM. If you can squash it into a handful of coherent and independent commits, that'd be great, but if its too hard or time consuming, just squash the thing down with one solid commit message.

**Comment by sgeto** [comment]
I removed the duplicates and rebased.  @sam-github I would go ahead and merge as is if that's fine with you.

**Comment by sam-github** [comment]
Could you rebase to fix the conflicts and force push?

Also, fails to build for me. After `git clean -x -d; ../Prepare; ../Build` I got:
```
% ../Build 
Makefile:1158: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.
``` 

Line in question is:
```
doc: doxygen-doc
        $(AM_V_GEN)cd $(DX_DOCDIR) && ./fixmanpages && cd -
                doc/libnet.chm
```

Note that the `doc/libnet.chm` has just leading spaces.

libnet config summary, if useful:

```
-=-=-=-=-=-=-=-=-= libnet Configuration Complete =-=-=-=-=-=-=-=-=-=-


Configuration Summary

    Version : ..................... 1.2-rc3
    Protocols: .................... 32

    Host : ........................ x86_64-apple-darwin17.5.0
    Operating System: ............. darwin17.5.0
    Host CPU : .................... x86_64
    Host Vendor : ................. apple
    Host OS : ..................... darwin17.5.0
    Prefix: ....................... /usr/local

Compilation Environment

    Cross-compiling: .............. no
    Compiler is GCC: .............. yes
    CC: ........................... gcc
    CFLAGS:........................ -O0 -g -Wall --coverage
    LD: ........................... /Library/Developer/CommandLineTools/usr/bin/ld
    LDFLAGS: ...................... 
    LIBS: ......................... 

Features and Examples

    Link Layer: ................... bpf
    Shared Libraries: ............. yes
    Static Libraries: ............. yes
    PIC ........................... yes
    Debugging: .................... no
    Additional Optimizations: ..... no
    Build Sample Programs: ........ yes
    Rebuild docs: ................. no
```

**Comment by koeppea** [comment]
Needed to reinstall my FreeBSD VM.
Building master works fine.
`Build` fails similar for me:
```
$ ../Build 
make: "/usr/home/koeppea/dev/libnet/libnet/Makefile" line 1155: Need an operator
make: Fatal errors encountered -- cannot continue
make: stopped in /usr/home/koeppea/dev/libnet/libnet
$ 
```

**Comment by troglobit** [comment]
@barak @sgeto Hi, new guy here!  This pull request is quite big, but from what I understand " it incorporate #49 and replaces #58.".  Without spending too much time dissecting all of them, does this mean #49 and #58 can be closed if this one is merged?  

Great job btw with all this, we have changes on master already that conflicts hard with this one, but I'll untangle them if you can just help me establish the relationship with the other PR's, thanks! :-)

**Comment by troglobit** [comment]
ETIMEDOUT, will untangle all these related pull requests manually.  As a result, anything that doesn't build or work, at my own discretion, will be dropped from the PRs.  We welcome of course new PRs to amend to this.

**Pull request merged**
