### PR TITLE
Cleanup bin --- not really working

### PR DESCRIPTION
**Pull request by sam-github**
I tried to cleanup bin, but am still getting:
```
make  distdir-am
if test -d "libnet-1.2-rc4"; then find "libnet-1.2-rc4" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "libnet-1.2-rc4" || { sleep 5 && rm -rf "libnet-1.2-rc4"; }; else :; fi
test -d "libnet-1.2-rc4" || mkdir "libnet-1.2-rc4"
 (cd bin && make  top_distdir=../libnet-1.2-rc4 distdir=../libnet-1.2-rc4/bin \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
```

Any idea why? Maybe we still need a `bin/Makefile.am`, but it should be empty?

### CODE REVIEW

**Comment by troglobit** [comment]
I think you must remove bin from `SUBDIRS=` in the top Makefile.am as well. 

Other than that, thank you! I was a bit hesitant to ask if you were married to these scripts :)

**Comment by sam-github** [comment]
I'll keep the ones I want locally. I left `bin/Changelog` there, remove it if you don't use it.

Note that they documented the maintenance process. Please do update `doc/RELEASE-CHECKLIST.txt`, ATM, you are the only one who knows how to release to GH.

**Comment by sam-github** [comment]
I force pushed, Travis is building the wrong commit, I guess I'll have to wait until its done then push again.

**Comment by troglobit** [comment]
Awesome, I'll update the build/release/contrib doc later, promise!  This PR looks excellent and I'll merge it as soon as Travis is happy.

**Pull request merged**
